### ISSUE TITLE
ERROR: set_fact is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by 0vermind** [debops/debops-tools#102]
Hi guys  great project!
Just installed via apt + pip (ubuntu lts 14.04) following the docs, but i get when i try to start debops in myproject dir.
What kind of problem could it be?

> ERROR: set_fact is not a legal parameter in an Ansible task or handler

**Comment by drybjed** [comment]
@0vermind How did you install Ansible? It looks like you don't have Ansible modules installed.

**Comment by 0vermind** [comment]
I installed it via apt and I'm sure plugins are there because I can use words like apt: or user: which are core modules.

**Comment by drybjed** [comment]
@0vermind In that case `set_fact` should also work because it's a core module... Did you install current stable Ansible (1.9) ?

**Comment by 0vermind** [comment]
you where right but I don-t understand what is happening:
the playbooks in /debops is empty!

> ansible 1.5.4

I was hoping to have a newer version.

Thanks for the hints. I am Upgrading right now.

**Comment by drybjed** [comment]
After you install `debops` through `pip`, you need to run `debops-update` to download all the roles and playbooks from GitHub.

**Comment by 0vermind** [comment]
Shame on me, I was too distracted then I was following the guide. I managed to run debops flawlessly after the ugrade.
I still have a bit of problems accessing a server using my ssh key but I digging into that. Using ssh from command line works, 

> sss [server] -i /path/to/key 

but not from ansible or debops.
Thanks a lot for the fast help, wow, insane.

**Comment by drybjed** [comment]
@0vermind Ansible / DebOps uses your `ssh` settings to access the remote hosts. If you use a different key than `~/.ssh/id_rsa`, then you need to point to that key in the Ansible inventory, using `ansible_ssh_authorized_key` parameter, IIRC. Or you could set it up in `~/.ssh/config` as well, just remember to use `ssh` connection plugin in Ansible instead of paramiko.
