### ISSUE TITLE
su doesn't require password

### ISSUE THREAD

**Issue by Zorlin** [debops/debops-tools#110]
Hi there,

From an admin/sudo user, if you type "su" and hit enter it drops you straight into a root shell.

Feature or bug?

**Comment by Zorlin** [comment]
By design, from what tobijb and I could ascertain.

<tobijb> https://github.com/debops/ansible-auth/blob/master/templates/etc/pam.d/su.j2#L22

**Comment by drybjed** [comment]
It's by design but using some more PAM-based security (Yubikey? SSH agent?) could be added in the future. Root password is randomized so kind of hard to use `su` with it.
