### ISSUE TITLE
Ubuntu Studio Trusty installation fails

### ISSUE THREAD

**Issue by devekko** [debops/debops-tools#126]
I am running into a mess of Python 3.4 related issues with Ubuntu Studio Trusty when installing debops

had a much better time on mainline Trusty

am thinking of running a VirtualBox of Jessie as a bastion server just to get this thing to run !

cheers

-N

**Comment by devekko** [comment]
you know what, I hate Vagrant, will do an encrypted proxmox vm instead

**Comment by drybjed** [comment]
@devekko I don't use Vagrant either, instead I have a normal, separate subnet with `dnsmasq` serving as DNS, DHCP and PXE boot service, and I'm using KVM host for virtual machines, which hold LXC containers. That way I get more permanent setup that is actually on a remote server in a data center, and I connect through it using `tinc` VPN. All is on its own separate subdomain, mail works, I don't even use IP addresses, just hostnames.

As for ubuntu Studio not working... I dunno. I write DebOps for Debian first, so it should always work there. If you can tell me what specific issues with US you got, maybe we can find solutions.

**Comment by devekko** [comment]
was thinking of making a bastion debops controller server on Jessie and expect fewer issues

but, can I replicate or backup the debops controller server if its not my laptop? 

the main issue on Ubuntu Studio was Python 3.4 .. ConfigParser from memory

it was a late night special I am afraid, will try again from another clean install of Ubuntu Studio

I guess I should get it running from my main laptop

but, am wondering how I should replicate/backup, especially secrets

**Comment by devekko** [comment]
niccolox@trustyinx:~|⇒  debops-update
Traceback (most recent call last):
  File "/usr/local/bin/debops-update", line 63, in <module>
    from debops import *
  File "/usr/local/lib/python3.4/dist-packages/debops/**init**.py", line 42, in <module>
    from .config import *
  File "/usr/local/lib/python3.4/dist-packages/debops/config.py", line 108
    except ConfigParser.Error, e:
                             ^
SyntaxError: invalid syntax
niccolox@trustyinx:~|⇒  sudo pip install https://github.com/debops/debops/archive/master.zip
[sudo] password for niccolox: 
Sorry, try again.
[sudo] password for niccolox: 
The directory '/home/niccolox/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/niccolox/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://github.com/debops/debops/archive/master.zip
  Downloading https://github.com/debops/debops/archive/master.zip
     \ 73kB 409kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-6_0pps19-build/setup.py", line 52, in <module>
        zip_safe = True,
      File "/usr/lib/python3.4/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3.4/distutils/dist.py", line 394, in parse_config_files
        parser.read(filename)
      File "/usr/lib/python3.4/configparser.py", line 672, in read
        self._read(fp, filename)
      File "/usr/lib/python3.4/configparser.py", line 1070, in _read
        fpname, lineno)
    configparser.DuplicateOptionError: While reading from 'setup.cfg' [line 12]: option 'release' in section 'aliases' already exists

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-6_0pps19-build

**Comment by devekko** [comment]
niccolox@trustyinx:~|⇒  sudo -H pip install https://github.com/debops/debops/archive/master.zip
Collecting https://github.com/debops/debops/archive/master.zip
  Downloading https://github.com/debops/debops/archive/master.zip (72kB)
    100% |████████████████████████████████| 73kB 230kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-sfm3dcta-build/setup.py", line 52, in <module>
        zip_safe = True,
      File "/usr/lib/python3.4/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3.4/distutils/dist.py", line 394, in parse_config_files
        parser.read(filename)
      File "/usr/lib/python3.4/configparser.py", line 672, in read
        self._read(fp, filename)
      File "/usr/lib/python3.4/configparser.py", line 1070, in _read
        fpname, lineno)
    configparser.DuplicateOptionError: While reading from 'setup.cfg' [line 12]: option 'release' in section 'aliases' already exists

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-sfm3dcta-build

**Comment by devekko** [comment]
I did do a bit of hacking trying to get the ConfigParser references to lower case

but, its not sustainable ... 

niccolox@trustyinx:~|⇒  sudo -H pip install --upgrade virtualenv  
Requirement already up-to-date: virtualenv in /usr/local/lib/python3.4/dist-packages
niccolox@trustyinx:~|⇒  sudo -H pip install --upgrade pip  
Requirement already up-to-date: pip in /usr/local/lib/python3.4/dist-packages/pip-7.1.2-py3.4.egg
niccolox@trustyinx:~|⇒  sudo -H pip install debops
Requirement already satisfied (use --upgrade to upgrade): debops in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/local/lib/python3.4/dist-packages (from debops)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/local/lib/python3.4/dist-packages (from debops)
niccolox@trustyinx:~|⇒  sudo -H pip install --upgrade debops
Requirement already up-to-date: debops in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: netaddr in /usr/local/lib/python3.4/dist-packages (from debops)
Requirement already up-to-date: argparse in /usr/local/lib/python3.4/dist-packages (from debops)
niccolox@trustyinx:~|⇒  debops-init ~/debops-devekko  
Traceback (most recent call last):
  File "/usr/local/bin/debops-init", line 38, in <module>
    from debops import *
  File "/usr/local/lib/python3.4/dist-packages/debops/**init**.py", line 42, in <module>
    from .config import *
  File "/usr/local/lib/python3.4/dist-packages/debops/config.py", line 108
    except ConfigParser.Error, e:
                             ^
SyntaxError: invalid syntax

**Comment by devekko** [comment]
https://github.com/debops/debops/blob/6daddec4f73e69fd39c44197b5c9952f1f2cf368/setup.py

so, Ubuntu has both 2.7 and 3.4 of Python running

but, debops uses 2.7

so, I guess I should be finding a way to switch / run the debops-init type commands under 2.7 on Trusty

niccolox@trustyinx:~|⇒   python -V
Python 2.7.6
niccolox@trustyinx:~|⇒   python3 -V
Python 3.4.0

presumably there is a way to do this in code also

**Comment by devekko** [comment]
judging from this http://stackoverflow.com/questions/11756777/how-to-change-the-default-version-of-python-in-a-linux-machine-not-just-symlin

its not smart to try to change defaults on python

so, am going to spin up a Vagrant Jessie VM on my laptop and see if I can make this work

the strange thing is I am sure I got this working on mainline Trusty, so, maybe there enough of a difference between Ubuntu Studio and Trusty mainline

**Comment by devekko** [comment]
just did an pip uninstall

then

niccolox@trustyinx:~/Projects|⇒  git clone https://github.com/debops/debops
Cloning into 'debops'...
remote: Counting objects: 1142, done.
remote: Total 1142 (delta 0), reused 0 (delta 0), pack-reused 1142
Receiving objects: 100% (1142/1142), 240.27 KiB | 0 bytes/s, done.
Resolving deltas: 100% (652/652), done.
Checking connectivity... done.
niccolox@trustyinx:~/Projects|⇒  sudo pip install ./debops
The directory '/home/niccolox/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/niccolox/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./debops
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-zyx4rezy-build/setup.py", line 52, in <module>
        zip_safe = True,
      File "/usr/lib/python3.4/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3.4/distutils/dist.py", line 394, in parse_config_files
        parser.read(filename)
      File "/usr/lib/python3.4/configparser.py", line 672, in read
        self._read(fp, filename)
      File "/usr/lib/python3.4/configparser.py", line 1070, in _read
        fpname, lineno)
    configparser.DuplicateOptionError: While reading from 'setup.cfg' [line 12]: option 'release' in section 'aliases' already exists

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-zyx4rezy-build

**Comment by devekko** [comment]
got passed install from git repo by commenting out redudant line

# release = egg_info sdist register

release = egg_info sdist register upload upload_docs

then, init fails again

niccolox@trustyinx:~/Projects|⇒  debops-init ~/debops-devekko  
Traceback (most recent call last):
  File "/usr/local/bin/debops-init", line 38, in <module>
    from debops import *
  File "/usr/local/lib/python3.4/dist-packages/debops/**init**.py", line 32, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

**Comment by devekko** [comment]
tried this, 
sudo apt-get install python3-dev
failed 

maybe you can use the Six module, for Python 2 & 3 compatability
http://pythonhosted.org/six/

**Comment by devekko** [comment]
somehow Ansible is broken 

I think I might have stumbled into this bug, probably by trying various installation methods, possibly without correct permissions

https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1308714

which is similar to 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/O3CFSXB_UhM/FzrMPX2oLQAJ

havent reinstalled on a fresh Ubuntu Studio, but did get it working no problem on Trusty

**Comment by drybjed** [comment]
@devekko You could try building a `.deb` Ansible package from GitHub source using `LANG=C make deb` command, then installing the resulting `.deb` via `dpkg -i`.

DebOps should now work correctly with Ansible v2 (devel), so you can try using this version, although in production I would still use current stable release.

**Comment by devekko** [comment]
am closing this, for this new more general one https://github.com/debops/debops/issues/127
