### ISSUE TITLE
Change "his program" to "This Program" in all roles.

### ISSUE THREAD

**Issue by ypid** [debops/debops-tools#128]
The problem from https://github.com/debops/debops-playbooks/pull/198 seems to be present in all roles.

```
ag '\bhis program' -a
```

I would recommend to fix this in using `sed`. #120

**Comment by drybjed** [comment]
Arrgh. Yeah, I'm gonna do this. :-)

**Comment by ypid** [comment]
Also note that the version of the GPL is not present. Compare with https://www.gnu.org/licenses/gpl-3.0.de.html (bottom).

**Comment by ypid** [comment]
Should be fixed now. Closing so that this repo can be archived eventually.
