### ISSUE TITLE
bootstrap-ansible.sh does not work with recent tags (v1.9.4-1)

### ISSUE THREAD

**Issue by Gomez** [debops/debops-tools#131]
I executed it like this:

```
./misc/scripts/bootstrap-ansible.sh v1.9.4-1
```

The "-1" in the version mixup the deb install, and nothing get installed.

**Comment by drybjed** [comment]
Will check this issue, thanks.

**Comment by drybjed** [comment]
@Gomez Script should work now.

**Comment by Gomez** [comment]
Works thx! (I worked on the solution as well :))
