### ISSUE TITLE
Instructions in Getting Started don't work, path to 'core' missing?

### ISSUE THREAD

**Issue by ariddell** [debops/debops-tools#141]
I'm following the instructions in Getting Started but I'm hitting this error when I run `debops`

```
Running Ansible playbook from:
/home/user/.local/share/debops/debops-playbooks/playbooks/site.yml ...
ERROR: cannot find role in /home/user/.local/share/debops/debops-playbooks/playbooks/roles/debops.core or /home/user/.local/share/debops/debops-playbooks/playbooks/debops.core or /etc/ansible/roles/debops.core
```

Here's the contents of playbooks/

```
app  callback_plugins  env  filter_plugins  hw  library  lookup_plugins  net  service  srv  sys  tools  virt  app.yml  bootstrap.yml  common.yml  core.yml  env.yml  hw.yml  net.yml  site.yml  srv.yml  sys.yml  virt.yml
```

Anything I can do to fix this?

**Comment by drybjed** [comment]
Did you run `debops-update` command to download all the roles? Presumably, yes since you have the playbook... Is there anything in `~/.local/share/debops/debops-playbooks/roles/`? What OS do you use on your Ansible Controller, Linux, MacOSX, Windows?

**Comment by ariddell** [comment]
Strange. I started over from a clean virtualenv and the problem is gone! Thanks.

**Comment by drybjed** [comment]
Ah, `virtualenv`... Haven't got that concept yet. I just use LXC containers instead, easier to understand. :)
