### ISSUE TITLE
gen_ansible_cfg in bin/debops disabled

### ISSUE THREAD

**Issue by sread** [debops/debops-tools#142]
Unless I'm mistaken, the call to gen_ansible_cfg was accidentally commented out in 96e29e227d1874aae9afb12a57ceb02b20923e17 (#134). Doesn't seem relevant to the rest of the commit and it breaks generating the ansible.cfg file for me.

**Comment by drybjed** [comment]
Calling @ypid to the scene of the crime...

**Comment by ypid** [comment]
Damn. I had those lines commented out in my working copy (in lake of a better fix for now because I did/do some stuff in my ansible.cfg). Sorry that the file slipped into the commit … Thanks to @sread for finding and fixing :+1:
