### ISSUE TITLE
Use SPDX license identifiers

### ISSUE THREAD

**Issue by ypid** [debops/debops-tools#155]
Ref: https://github.com/ansible/galaxy-issues/issues/169 (not yet approved)

I am already doing this, ref:
- https://github.com/debops/ansible-cryptsetup/blob/master/meta/main.yml
- https://github.com/debops/ansible-apt_cacher_ng/blob/master/meta/main.yml

And Galaxy does not have any problem with it.

**Comment by drybjed** [comment]
Sounds good. :+1: I'll start to update it in the roles I'm woking on.

**Comment by ypid** [comment]
We are doing that now extensively ;-) Closing so that this repo can be archived eventually.
