### ISSUE TITLE
Refactor repo and rename to debops-tools.

### ISSUE THREAD

**Issue by ypid** [debops/debops-tools#156]
I propose the name "DebOps Tools" for this repository to avoid misunderstanding what this repo is about. Maybe a new debops/debops repo can be created as a landing page and general issue tracker.

**Comment by drybjed** [comment]
Sounds goot. This should probably involve @danstender to update the packaging in Debian, as well as changes on PyPI.

**Comment by ypid** [comment]
Things are still progressing and evolving. I am closing this. Newest work: https://github.com/debops/debops/pull/1455/files
