### ISSUE TITLE
MS Windows Support?

### ISSUE THREAD

**Issue by ypid** [debops/debops-tools#176]
AFAIK Ansible only reliably runs on UNIX. I don’t think it makes sense to mention MS Windows somewhere. I don’t see a good reason to support that platform. Or do we have actual users on Windows?

Refs:
* https://en.wikipedia.org/wiki/User:AnBuKu/DebOps
* https://docs.debops.org/en/latest/debops/docs/configuration.html

**Comment by drybjed** [comment]
Do you mean DebOps being used on Windows to manage Linux hosts? Or DebOps being used to manage Windows?

For the first case, I know that some people tried to do it, with varying success. I think that CygWin was involved, or you can use a VM to run Ansible inside.

For the second case, GNU/Windows exists, which is based on Ubuntu, which is supported by DebOps to some extent. How much of that environment could be managed by DebOps - I have no idea. If you find out, let me know. :-)

**Comment by ypid** [comment]
I don’t feel the urge to try out either of them :wink:

> Do you mean DebOps being used on Windows to manage Linux hosts?

Yes, that is what I meant. What DebOps targets itself is well defined (Debian or Debian derivatives). I think it should be mentioned that Windows is not officially supported then and link to workarounds or so if there are as I am not confinced that it would be ideal to have a wiki entry about DebOps which says that Windows as a platform for the Ansible Controller is supported by us :wink:

**Comment by drybjed** [comment]
Sure, I suppose that we can remove that part of the documentation, unless somebody shows up and tell use that it actually works. ;-)

**Comment by ypid** [comment]
I guess people now use DebOps in WSL. I have not tried it. Closing so that this repo can be archived eventually.

**Comment by nickjj** [comment]
Just chiming in to say that Ansible, Bash and friends all work nicely on WSL / WSL 2.
