### ISSUE TITLE
ansible/inventory/group_vars/all/apt_lxc.yml must be stored as a dictionary/hash

### ISSUE THREAD

**Issue by htgoebel** [debops/debops-tools#61]
I get this error when running a playbook on a freshly created debops project.
This file currently contains only comments. Obviously Ansible does not like this. I'm afraid, the only way to avoid this error message is to remove the file.

```
mkdir /tmp/testtesttest
cd /tmp/testtesttest
debops-init
echo localhost >> ansible/inventory/hosts
cat > site.yml <<EOF

---
- gather_facts: false
  hosts: localhost
  tasks:
  - name: Check if host is in group
    command: echo "yes"
EOF
debops ./site.yml
```

**Comment by drybjed** [comment]
Those two variables are not normally needed, and I suppose that perhaps a FAQ page in documentation with prominent link to it on the home page would better serve as a way to find solutions for common problems. And I'm in favor of not forcing a particular inventory layout either on the user. `apt_lxc.yml` can be removed.

**Comment by htgoebel** [comment]
The new version of `debops-init` no longer creates this file.
