### ISSUE TITLE
Debops system-wide installation option(s)

### ISSUE THREAD

**Issue by rchady** [debops/debops-tools#85]
DebOps used to do a system-wide installation in to /usr/local.  Since v0.2.0, it no longer does and instead installs in $HOME/.local.  This might work well when you have a single person working with DebOps, but once you have more than one, the system-wide installation is required.

A suggestion I have is to have debops default to using a global /etc/debops.conf file whose location can be overridden by an environment variable, or a command line arg... or both.  In there you can set what the prefix is for the installation path.  That way you can support user and system-wide installations.

**Comment by drybjed** [comment]
Pinging @htgoebel for this issue. :-)

**Comment by htgoebel** [comment]
Okay, I'll implement the feature. Will take some time, though.
