### ISSUE TITLE
ansible-playbook cannot be interrupted with Ctrl-C

### ISSUE THREAD

**Issue by drybjed** [debops/debops-tools#94]
When `debops` passes control to `ansible-playbook`, pressing Control+C does not stop the playbook execution. Is there something we could do to fix this?

**Comment by htgoebel** [comment]
I'll have a look at it next week.

**Comment by htgoebel** [comment]
I can not reproduce this. Ctrl-C works fine here on a Linux system.

```
TASK: [my.base | Set keyboard layout] ************************************* 
ok: [server] => (item={'key': 'XKBLAYOUT', 'value': u'de'})
^C... abortedERROR: interrupted
```

Do you have this problem on Linux or on a different platform?

**Comment by drybjed** [comment]
On Linux. And yeah, I just tested it and it works again. Weird. Maybe that was something else at the time. OK, I'll close this issue for now and see what happens.
